music.play(music.stringPlayable("C5 B A G F E D C ", 120), music.PlaybackMode.UntilDone)
basic.showIcon(IconNames.Yes)
basic.showString("VAS DE TERCERAS")
basic.showString("VAS DE SEGUNDAS ")
basic.showString("¡¡PELIGRO DE ACCIDENTALIDAD!!")
music.play(music.stringPlayable("A F E F D G E F ", 120), music.PlaybackMode.UntilDone)
basic.showIcon(IconNames.No)
music.ringTone(988)
basic.showString("LO SIENTO , ACABAS DE ESTRELLARTE")
music.play(music.stringPlayable("C5 A B G A F G E ", 120), music.PlaybackMode.UntilDone)
